### ISSUE TITLE
No callback for verifyEmail when user is not found with given token

### ISSUE THREAD

**Issue by prasadadss** [heitortsergent/passport-local-mongoose-email#6]
schema.statics.verifyEmail = function(authToken, cb) {
    var self = this;
    self.findByAuthToken(authToken, function(err, user) {
        if (err) { return cb(err); }

```
    if(user) {
        user.isAuthenticated = true;
        user.save(function(err) {
            if (err) {
                return cb(err);
            }
            cb(null, user);
        });
    }
    //else {cb(null, null)}   <------ this part is actually missing
});
```

};

No callback is executed if user is not found. So server is waiting for callback to be triggered and cannot give response to the client/user

**Comment by heitortsergent** [comment]
Closed by #9
